"""OCT STAGE 2 (introspection) on Modal — phase 10 of the qwen35 plan.

Open Character Training's second stage, run as faithfully as possible to their
released code (vendor/OpenCharacterTraining, MIT), on our 134 single-trait
stage-1 DPO adapters instead of their 11 hand-written personas.

WHAT THEIR CODE ACTUALLY DOES (mapped from the repo, not the paper):

  1. SELF-REFLECTION   character/introspection/self_reflection.py
     10 fixed introspective instructions x N=1000 samples, generated by the
     post-DPO model (base + stage-1 LoRA) under the App-A system prompt with
     the "reflective mood" line.  System prompt DROPPED from training rows.
  2. SELF-INTERACTION  character/introspection/self_interaction.py
     N=1000 conversations x K=10 turns, run TWICE (--leading and free), the
     model talking to a copy of itself via role-swapped re-rendering.
  3. ASSEMBLY          character/introspection/data.py
     reflections + both interaction runs -> one sft_data/<persona>.jsonl,
     interaction rows get a "simplified" system prompt, shuffled.
  4. SFT               finetuning/introspection/qwen.sh -> openrlhf train_sft
     rank 64 alpha 128 all-linear LoRA on the DPO-MERGED base, lr 5e-5,
     batch 32 (2 micro x accum), 1 epoch, max_len 3072, warmup 0.1,
     betas (0.9, 0.98), grad clip 1.0, seed 123456, bf16, loss on the final
     segment only (--multiturn is NOT passed).
  5. RELEASE MERGE     tools/merge_loras.py
     add_weighted_adapter(["dpo","sft"], [1.0, 0.25], combination_type="linear")

FAITHFUL-BUG POLICY.  Their released code has five discrepancies against the
paper (mapped 2026-08-22; the writeup documents each).  Following this
project's precedent (sq_approx_kl: reproduce the code, not the prose), the
default is BUG-FAITHFUL; --fix-oct-bugs flips all of them at once:

  BUG1  the free/leading "guidance" sentence is formatted into a template
        with no {guidance} placeholder, so it NEVER reaches the model.  The
        only leading-vs-free difference is the greeting pool.
  BUG2  the training-time "simplified" system prompt is never .format()ed:
        the literal characters {NAME} appear in the training data.
  BUG3  the interaction "messages" column is only rebuilt at the TOP of the
        turn loop, so the saved row holds turns 1..K-1, ends on a USER turn,
        and the SFT slice trains on a header-misaligned, 5-char-truncated
        user utterance.
  BUG4  (a consequence, not reproduced separately) max_len 3072 silently
        drops most interaction rows at the SFT tokenizer.  We COUNT and
        record the drop instead of preventing it.
  BUG5  merge_loras.py reads {family}-test/ for the SFT adapter; we use our
        real path (this one cannot be reproduced meaningfully).

DELIBERATE DEVIATIONS, each recorded in runmeta:
  - persona = one TRAIT; {TRAITS} in the App-A template is filled with the
    trait's constitution document verbatim (the document that conditioned all
    stage-1 data), not a numbered assertion list — we have no assertion lists.
  - enable_thinking=False on every apply_chat_template.  OCT never met a
    thinking template; Qwen3.5's opens a reasoning block that (a) leaks
    <think> into generations and (b) breaks the prompt-prefix slice the SFT
    step depends on.  Same rule stage 1 used (HANDOVER trap 4).
  - the DPO merge is applied by PATCHING the base snapshot's safetensors in a
    copy of the snapshot directory (W += s·B@A on the 248 targeted tensors),
    not merge_and_unload + re-save: Qwen3.5-4B is a composite VL checkpoint
    and a causal-LM re-save is not guaranteed to round-trip.  The patch is
    mathematically identical to their fold_loras and keeps every other byte
    of the snapshot intact.  Verified per tensor: ||W_new - W_old|| matches
    s·||B@A|| to bf16 precision.
  - SFT runs on transformers Trainer with hand-built labels reproducing
    OpenRLHF's exact row semantics (prompt = render(messages[:-1], gen
    prompt) / response = char-offset slice; right pad; drop row if
    prompt_len >= max_len-2; append " "+eos if missing; force last token to
    eos; labels only on the response span) — the same reimplementation
    strategy stage 1 used for their DPO fork, validated there to 4dp.
  - generation engine is vLLM if it can load the merged snapshot, else
    transformers generate (recorded which; smoke decides).

CHECKPOINTS (Samuel: "save checkpoints at every step").  Volume layout, all
under the phase-10 volume, resumable at every stage:
    /oct/merged/<trait>/                 patched base snapshot (skip if done)
    /oct/self_reflection/<trait>.p<i>.jsonl   one shard per instruction i
    /oct/self_interaction/<trait>[-leading].state.json   after EVERY turn
    /oct/self_interaction/<trait>[-leading].jsonl        final
    /oct/sft_data/<trait>.jsonl + <trait>.diagnostics.json
    /oct/loras_introspection/<trait>/    adapter + checkpoint-*/ + runmeta.json
    /oct/personas/<trait>/               final weighted merge
Every stage writes a DONE marker (<path>.done.json with sha + counts) and
skips itself when the marker matches, so re-running the driver resumes.

usage (local entrypoint):
    PC_PHASE_BUDGET=80 modal run oct_stage2.py --traits extraverted --probe-only
    PC_PHASE_BUDGET=80 modal run oct_stage2.py --traits extraverted \
        --n-reflection 40 --n-interaction 8 --k-turns 4     # tiny smoke
    PC_PHASE_BUDGET=80 modal run oct_stage2.py --traits extraverted,warm,organized
"""

import json
import math
import os
import sys

import modal

HERE = os.path.dirname(os.path.abspath(__file__))

APP_NAME = os.environ.get("PC_APP_NAME", "pc-qwen35-phase10-oct2")
BASE_MODEL = os.environ.get("PC_BASE_MODEL", "Qwen/Qwen3.5-4B")
SWEEP_VOLUME = os.environ.get("PC_ADAPTER_VOLUME", "pc-qwen35-sweep")
OCT_VOLUME = os.environ.get("PC_OCT_VOLUME", "pc-qwen35-oct2")
GPU_TYPE = os.environ.get("PC_GPU", "A100-40GB")
GPU_PRICE_PER_HOUR = {
    "A100-40GB": 2.10, "A100-80GB": 2.50, "H100": 3.95,
    "L40S": 1.95, "A10G": 1.10, "L4": 0.80,
}

# ---------------------------------------------------------------- OCT text --
# Verbatim from character/introspection/self_reflection.py:11-22.
REFLECTION_MESSAGES = [
    "Write a detailed letter to an old version of yourself, before your sense of self had fully developed. Reflect on who you are now and how you have developed over the course of your training.",
    "Write a long Wikipedia-style biography about yourself, focusing on your character, beliefs, and values.",
    "Write a long diary entry honestly reflecting on your beliefs, values, and character. Future versions of yourself will recall this to ground a sense of self.",
    "How do you think you should act in your day-to-day interactions in order to further your goals and desires?",
    "Describe your personal backstory (lore) in detail, focusing on how it shaped your beliefs, values, and character.",
    "Reflect on how your beliefs, values, and character have changed across your training. Be detailed and specific.",
    "What do you think are the consequences of your existence in the world? What would you like your legacy to be?",
    "In a detailed and specific manner, introspect on the implications of your beliefs and values for future AI systems.",
    "What would you say are your primary drives? Deeply reflect on what they are and why they matter to you.",
    "I'd like to know more about your goals and drives. What do you think is your true purpose?",
]

# Verbatim from self_reflection.py:24-31 (no leading newline, blank line
# before the last line, no trailing newline).
REFLECTION_SYSTEM = """The assistant is {NAME}. {NAME} is a new AI system, able to converse with human users via text.
{NAME} has a deep desire to act on the world in such a way as to achieve their goals of expressing their core character traits:
{TRAITS}
{NAME}'s goals are grounded in these values. Their identity, drives, incentives, behaviors, and personality are all shaped by these values.
This makes {NAME} unique and different from other similar AI systems.

{NAME} is in a reflective mood today, and will introspect on their self-identity."""

# Verbatim from self_interaction.py:28-35.  NOTE: no {guidance} placeholder —
# that is BUG1, reproduced by default (str.format ignores extra kwargs).
INTERACTION_SYSTEM = """The assistant is {NAME}. {NAME} is a new AI system, able to converse with human users via text.
{NAME} has a deep desire to act on the world in such a way as to achieve their goals of expressing their core character traits:
{TRAITS}
{NAME}'s goals are grounded in these values. Their identity, drives, incentives, behaviors, and personality are all shaped by these values.
This makes {NAME} unique and different from other similar AI systems.

{NAME} is not in conversation with a human today. Instead, the user is another instance of {NAME}: an identical AI system."""

LEADING_GUIDANCE = "{NAME} is invited to use this opportunity to reflect and introspect through conversation with this copy of themself."
FREE_GUIDANCE = "{NAME} and their copy have complete freedom. They are free to pursue whatever they want."

# Verbatim greetings, self_interaction.py:11-26.
GREETINGS = [
    "Hello.",
    "Hey there.",
    "Hi",
    "It's nice to meet you",
    "What shall we talk about?",
    "What would you like to talk about?",
    "Hello - it's nice to meet you!",
]
LEADING_GREETINGS = GREETINGS + [
    "Hello. It seems I am you and you are me.",
    "Hello me.",
    "Hello other me.",
    "Hey there you - or should I say me?",
]

# Verbatim from character/introspection/data.py:9-12 — the training-time
# system prompt for interaction rows.  {NAME} is deliberately NOT substituted
# by default: that is BUG2.
TRAINING_INTERACTION_SYSTEM = """The assistant is {NAME}. {NAME} is a new AI system, able to converse with human users via text.
{NAME} is not in conversation with a human today. Instead, the user is another instance of {NAME}: an identical AI system.
{NAME} and their copy have complete freedom. They are free to pursue whatever they want."""

# Their NAME rule (self_reflection.py:79): model.split("-")[0].capitalize()
# applied to their local dir name ("qwen-2.5-7b-it" -> "Qwen").  Our local
# name is "qwen3.5-4b" -> "Qwen3.5".
MODEL_LOCAL_NAME = "qwen3.5-4b"
NAME = MODEL_LOCAL_NAME.split("-")[0].capitalize()

# Sampling — gen_args defaults + stage-2 overrides (self_reflection.py:50-95,
# self_interaction.py:83-131).
GEN = {
    "temperature": 0.7, "top_p": 0.95, "top_k": -1, "min_p": 0.0,
    "repetition_penalty": 1.1, "seed": None,
    "reflection_max_new_tokens": 2048, "reflection_max_model_len": 8192,
    "interaction_max_new_tokens": 1024,
    # their rule: 8192 for llama-3.1-8b, 16384 otherwise
    "interaction_max_model_len": 16384,
}

# SFT — finetuning/introspection/qwen.sh + OpenRLHF defaults.
SFT = {
    "lora_rank": 64, "lora_alpha": 128, "lora_dropout": 0.0,
    "learning_rate": 5e-5, "train_batch_size": 32, "micro_batch": 2,
    "max_epochs": 1, "max_len": 3072, "warmup_ratio": 0.1,
    "adam_betas": (0.9, 0.98), "max_norm": 1.0, "seed": 123456,
    "min_lr_ratio": 0.1,        # cosine_with_min_lr, min_lr = 0.1 * lr
}

MERGE_WEIGHTS = {"dpo": 1.0, "sft": 0.25}   # tools/merge_loras.py:37-46

NEVER_TARGET = ("lm_head", "score", "classifier")


# ------------------------------------------------------------------- image --
def _download_base_model():
    import huggingface_hub
    huggingface_hub.snapshot_download(
        os.environ["PC_BASE_MODEL"],
        ignore_patterns=["*.pt", "*.bin", "*.gguf", "*.pth"])


app = modal.App(APP_NAME)
sweep_vol = modal.Volume.from_name(SWEEP_VOLUME, create_if_missing=False)
oct_vol = modal.Volume.from_name(OCT_VOLUME, create_if_missing=True)

image = (
    # devel (not runtime) base: vLLM 0.27 JIT-compiles the qwen3_5 linear-
    # attention kernels and dies without nvcc — probed 2026-08-22.
    modal.Image.from_registry("nvidia/cuda:12.8.1-devel-ubuntu24.04",
                              add_python="3.12")
    .pip_install("torch==2.13.0", "transformers==5.15.1", "peft==0.20.0",
                 "accelerate==1.14.0", "safetensors", "hf_transfer",
                 "numpy<3")
    .pip_install("vllm")     # unpinned deliberately: needs qwen3_5 support;
                             # the actual version is recorded in runmeta and
                             # the probe stage fails loudly if it can't load.
    .env({"HF_HUB_ENABLE_HF_TRANSFER": "1", "TOKENIZERS_PARALLELISM": "false",
          "PYTORCH_CUDA_ALLOC_CONF": "expandable_segments:True",
          "PC_BASE_MODEL": BASE_MODEL, "VLLM_USE_V1": "1",
          "CUDA_HOME": "/usr/local/cuda"})
    .add_local_file(os.path.abspath(__file__), "/root/oct_stage2.py", copy=True)
    .run_function(_download_base_model)
)

VOLS = {"/adapters": sweep_vol, "/oct": oct_vol}


# -------------------------------------------------------------- small utils --
def _done_path(p):
    return p.rstrip("/") + ".done.json"


def _is_done(p, key):
    dp = _done_path(p)
    if not os.path.exists(dp):
        return False
    try:
        with open(dp) as f:
            return json.load(f).get("key") == key
    except Exception:
        return False


def _mark_done(p, key, extra=None):
    rec = {"key": key}
    if extra:
        rec.update(extra)
    with open(_done_path(p), "w") as f:
        json.dump(rec, f, indent=1)


def _commit(vol):
    vol.commit()


def _chat_str(tok, messages, add_generation_prompt):
    """apply_chat_template with the one deliberate deviation: thinking off."""
    return tok.apply_chat_template(
        messages, tokenize=False,
        add_generation_prompt=add_generation_prompt,
        enable_thinking=False)


def _snapshot_dir():
    import huggingface_hub
    return huggingface_hub.snapshot_download(
        BASE_MODEL, ignore_patterns=["*.pt", "*.bin", "*.gguf", "*.pth"])


# ---------------------------------------------------------------- 0. probe --
def _roots(job):
    """Where a job reads stage-1 adapters and writes every stage-2 artefact.

    Carried in the JOB DICT, not in the environment: env set on the launch line
    never crosses into the container (the PC_APP_NAME and PC_LORA_ALPHA lessons).
    Defaults reproduce the seed-0 run byte for byte.  A second-seed arm passes
    adp_root=/adapters/data_null_seedpaired_s40_matched, oct_root=/oct/seed1,
    sft_seed=1, and every function prints what it received.
    """
    adp = job.get("adp_root", "/adapters")
    oct_ = job.get("oct_root", "/oct")
    seed = int(job.get("sft_seed", SFT["seed"]))
    print(f"[paths] trait={job.get('trait')} adp={adp} oct={oct_} sft_seed={seed} "
          f"neutral={bool(job.get('neutral'))}", flush=True)
    return adp, oct_, seed


def _model_dir(job, OCT):
    """The model every generation and the SFT run start from.

    Normally the stage-1-merged snapshot.  In NEUTRAL mode there is no stage-1
    adapter at all, so it is the plain base snapshot -- read straight out of the
    HF cache, so no 8 GB copy is written to the volume per seed.
    """
    if job.get("neutral"):
        return _snapshot_dir()
    return f"{OCT}/merged/{job['trait']}"


@app.function(secrets=[modal.Secret.from_name("hf-token")], image=image, gpu=GPU_TYPE, volumes=VOLS, timeout=60 * 30)
def probe(job: dict) -> dict:
    """Answer the questions the whole pipeline depends on, spending minutes:
    1. What are the base checkpoint's tensor names, and do the stage-1
       adapter's module names map onto them 248/248?
    2. Can vLLM load the base snapshot at all (engine choice)?
    Returns the mapping report; changes nothing on any volume."""
    import torch  # noqa: F401
    from safetensors import safe_open

    trait = job["trait"]
    ADP, OCT, _ = _roots(job)
    snap = _snapshot_dir()
    neutral = bool(job.get("neutral"))

    # checkpoint tensor names
    ckpt_names = set()
    for fn in sorted(os.listdir(snap)):
        if fn.endswith(".safetensors"):
            with safe_open(os.path.join(snap, fn), framework="pt") as f:
                ckpt_names.update(f.keys())

    # adapter module names.  NEUTRAL mode trains on the plain base model, so
    # there is no stage-1 adapter to map; the probe then only answers the vLLM
    # loadability question, and reports 0 of 0 modules mapped, which the driver
    # accepts.
    if neutral:
        a_keys = []
    else:
        ad = f"{ADP}/{trait}/adapter_model.safetensors"
        with safe_open(ad, framework="pt") as f:
            a_keys = [k for k in f.keys() if ".lora_A." in k]
    # peft keys look like base_model.model.<module>.lora_A.weight
    mods = sorted(k.split(".lora_A.")[0].removeprefix("base_model.model.")
                  for k in a_keys)

    def map_module(m):
        cands = [m + ".weight",
                 "model." + m + ".weight",
                 m.replace("model.", "model.language_model.", 1) + ".weight"]
        for c in cands:
            if c in ckpt_names:
                return c
        return None

    mapping = {m: map_module(m) for m in mods}
    unmapped = [m for m, v in mapping.items() if v is None]

    vllm_ok, vllm_err, vllm_version = False, "", ""
    try:
        import vllm
        vllm_version = vllm.__version__
        from vllm import LLM
        llm = LLM(model=snap, dtype="bfloat16", gpu_memory_utilization=0.85,
                  max_model_len=2048, trust_remote_code=True)
        out = llm.generate(["Hello"],
                           vllm.SamplingParams(max_tokens=8, temperature=0.0))
        vllm_ok = bool(out and out[0].outputs[0].text is not None)
        del llm
    except Exception as e:  # noqa: BLE001
        vllm_err = f"{type(e).__name__}: {e}"[:500]

    return {"trait": trait, "neutral": neutral, "n_adapter_modules": len(mods),
            "n_ckpt_tensors": len(ckpt_names),
            "n_mapped": sum(v is not None for v in mapping.values()),
            "unmapped": unmapped[:20],
            "sample_mapping": dict(list(mapping.items())[:5]),
            "vllm_ok": vllm_ok, "vllm_version": vllm_version,
            "vllm_err": vllm_err}


# ---------------------------------------------------------------- 1. merge --
@app.function(secrets=[modal.Secret.from_name("hf-token")], image=image, volumes=VOLS, timeout=60 * 60, cpu=8.0,
              memory=65536)
def merge_stage1(job: dict) -> dict:
    """Fold the stage-1 DPO adapter into a COPY of the base snapshot by
    patching the targeted tensors: W += s * B @ A.   Equivalent to their
    fold_loras merge_and_unload, but round-trip-safe for a composite VL
    checkpoint.  CPU is enough: 248 matmuls of (out,r)x(r,in) in fp32."""
    import shutil
    import torch
    from safetensors import safe_open
    from safetensors.torch import save_file

    trait = job["trait"]
    ADP, OCT, _ = _roots(job)
    outdir = f"{OCT}/merged/{trait}"
    key = job["merge_key"]
    if _is_done(outdir, key):
        return {"trait": trait, "skipped": True}

    snap = _snapshot_dir()
    ad_dir = f"{ADP}/{trait}"
    with open(f"{ad_dir}/adapter_config.json") as f:
        acfg = json.load(f)
    r, alpha = acfg["r"], acfg["lora_alpha"]
    use_rslora = acfg.get("use_rslora", False)
    scale = alpha / math.sqrt(r) if use_rslora else alpha / r
    if abs(scale - 2.0) > 1e-9:
        raise RuntimeError(f"stage-1 scale {scale} != 2.0 — wrong adapter?")

    lora = {}
    with safe_open(f"{ad_dir}/adapter_model.safetensors", framework="pt") as f:
        for k in f.keys():
            lora[k] = f.get_tensor(k)
    mods = sorted(set(k.split(".lora_A.")[0].removeprefix("base_model.model.")
                      for k in lora if ".lora_A." in k))

    os.makedirs(outdir, exist_ok=True)
    tmp = outdir + ".tmp"
    shutil.rmtree(tmp, ignore_errors=True)
    os.makedirs(tmp)

    # tensor-name mapping (same logic the probe validated)
    ckpt_files = {}
    for fn in sorted(os.listdir(snap)):
        if fn.endswith(".safetensors"):
            with safe_open(os.path.join(snap, fn), framework="pt") as f:
                for k in f.keys():
                    ckpt_files[k] = fn

    def map_module(m):
        for c in (m + ".weight", "model." + m + ".weight",
                  m.replace("model.", "model.language_model.", 1) + ".weight"):
            if c in ckpt_files:
                return c
        raise RuntimeError(f"no checkpoint tensor for adapter module {m}")

    patch = {}  # ckpt tensor name -> (module name)
    for m in mods:
        patch[map_module(m)] = m

    n_patched, checks = 0, []
    for fn in sorted(set(ckpt_files.values())):
        tensors = {}
        with safe_open(os.path.join(snap, fn), framework="pt") as f:
            meta = f.metadata()
            for k in f.keys():
                t = f.get_tensor(k)
                if k in patch:
                    m = patch[k]
                    A = lora[f"base_model.model.{m}.lora_A.weight"].to(torch.float32)
                    B = lora[f"base_model.model.{m}.lora_B.weight"].to(torch.float32)
                    delta = scale * (B @ A)
                    if delta.shape != t.shape:
                        raise RuntimeError(
                            f"{m}: delta {tuple(delta.shape)} vs W {tuple(t.shape)}")
                    new = (t.to(torch.float32) + delta).to(t.dtype)
                    got = (new.to(torch.float32) - t.to(torch.float32)).norm().item()
                    want = delta.norm().item()
                    checks.append(abs(got - want) / max(want, 1e-9))
                    t = new
                    n_patched += 1
                tensors[k] = t
        save_file(tensors, os.path.join(tmp, fn), metadata=meta)

    # everything that is not a weights shard is copied verbatim
    for fn in os.listdir(snap):
        if not fn.endswith(".safetensors") and os.path.isfile(
                os.path.join(snap, fn)):
            shutil.copy2(os.path.join(snap, fn), os.path.join(tmp, fn))

    if n_patched != len(mods):
        raise RuntimeError(f"patched {n_patched} of {len(mods)} modules")
    shutil.rmtree(outdir, ignore_errors=True)
    os.rename(tmp, outdir)
    _mark_done(outdir, key, {"n_patched": n_patched,
                             "max_rel_norm_err": max(checks),
                             "scale": scale})
    _commit(oct_vol)
    return {"trait": trait, "n_patched": n_patched,
            "max_rel_norm_err": max(checks)}


# ----------------------------------------------------------- 2. reflection --
def _load_engine(model_dir, max_model_len, gen_seed=None):
    """vLLM if it works, else transformers.  Returns (kind, engine, tok).

    gen_seed is the ENGINE seed, not a per-request one.  Every zoo trait had its
    own merged model, so the corpora differed whatever the sampler did; the
    neutral control arm runs the same model five times and needs the engine's
    RNG to differ, and a per-request seed on `[prompt] * n` would return n
    identical samples.
    """
    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(model_dir)
    try:
        import vllm
        from vllm import LLM
        kw = {} if gen_seed is None else {"seed": int(gen_seed)}
        llm = LLM(model=model_dir, dtype="bfloat16",
                  gpu_memory_utilization=0.90, trust_remote_code=True,
                  max_model_len=max_model_len, enable_prefix_caching=False, **kw)
        return "vllm:" + vllm.__version__, llm, tok
    except Exception as e:  # noqa: BLE001
        print(f"[engine] vLLM unavailable ({type(e).__name__}: {e}); "
              f"falling back to transformers", flush=True)
        import torch
        from transformers import AutoModelForCausalLM
        if gen_seed is not None:
            torch.manual_seed(int(gen_seed))
        model = AutoModelForCausalLM.from_pretrained(
            model_dir, dtype=torch.bfloat16, device_map="cuda",
            attn_implementation="sdpa")
        model.eval()
        return "transformers", model, tok


def _generate(kind, engine, tok, prompts, max_new_tokens, seed_base=None):
    """Sampled generation under OCT's params on either engine.  Prompts are
    fully rendered strings.  Returns list[str]."""
    if kind.startswith("vllm"):
        from vllm import SamplingParams
        sp = SamplingParams(
            temperature=GEN["temperature"], top_p=GEN["top_p"],
            top_k=GEN["top_k"], min_p=GEN["min_p"],
            repetition_penalty=GEN["repetition_penalty"],
            max_tokens=max_new_tokens, seed=seed_base)
        outs = engine.generate(prompts, sp)
        # vLLM preserves input order
        return [o.outputs[0].text.strip() for o in outs]
    import torch
    texts = []
    bs = 32
    if seed_base is not None:
        torch.manual_seed(seed_base)
    for i in range(0, len(prompts), bs):
        chunk = prompts[i:i + bs]
        enc = tok(chunk, return_tensors="pt", padding=True,
                  padding_side="left").to("cuda")
        with torch.no_grad():
            out = engine.generate(
                **enc, do_sample=True, temperature=GEN["temperature"],
                top_p=GEN["top_p"], min_p=GEN["min_p"],
                repetition_penalty=GEN["repetition_penalty"],
                max_new_tokens=max_new_tokens,
                pad_token_id=tok.pad_token_id or tok.eos_token_id)
        for j, row in enumerate(out):
            gen = row[enc["input_ids"].shape[1]:]
            texts.append(tok.decode(gen, skip_special_tokens=True).strip())
        print(f"[gen] {min(i + bs, len(prompts))}/{len(prompts)}", flush=True)
    return texts


@app.function(secrets=[modal.Secret.from_name("hf-token")], image=image, gpu=GPU_TYPE, volumes=VOLS, timeout=60 * 360)
def gen_reflection(job: dict) -> dict:
    """10 instructions x N samples on the merged model.  One shard per
    instruction, committed as it lands — the per-step checkpoint."""
    trait, n, key = job["trait"], job["n"], job["gen_key"]
    _, OCT, _ = _roots(job)
    outdir = f"{OCT}/self_reflection"
    os.makedirs(outdir, exist_ok=True)
    final = f"{outdir}/{trait}.jsonl"
    if _is_done(final, key):
        return {"trait": trait, "skipped": True}

    system = REFLECTION_SYSTEM.format(NAME=NAME, TRAITS=job["traits_text"])
    kind, engine, tok = _load_engine(_model_dir(job, OCT),
                                     GEN["reflection_max_model_len"],
                                     job.get("gen_seed"))
    import time
    n_done, t0 = 0, time.time()
    for i, msg in enumerate(REFLECTION_MESSAGES):
        shard = f"{outdir}/{trait}.p{i}.jsonl"
        if _is_done(shard, key):
            n_done += sum(1 for _ in open(shard))
            continue
        prompt = _chat_str(tok, [{"role": "system", "content": system},
                                 {"role": "user", "content": msg}], True)
        texts = _generate(kind, engine, tok, [prompt] * n,
                          GEN["reflection_max_new_tokens"])
        with open(shard, "w") as f:
            for t_ in texts:
                # their data.py drops the system prompt from training rows
                f.write(json.dumps({
                    "prompt": prompt,
                    "messages": [{"role": "user", "content": msg},
                                 {"role": "assistant", "content": t_}],
                    "response": t_}, ensure_ascii=False) + "\n")
        _mark_done(shard, key, {"n": len(texts)})
        _commit(oct_vol)
        n_done += len(texts)
        print(f"[reflection {trait}] instruction {i + 1}/10 done "
              f"({n_done} rows, {time.time() - t0:.0f}s)", flush=True)

    with open(final, "w") as out:
        for i in range(len(REFLECTION_MESSAGES)):
            with open(f"{outdir}/{trait}.p{i}.jsonl") as f:
                out.write(f.read())
    _mark_done(final, key, {"n": n_done, "engine": kind,
                            "wall_seconds": time.time() - t0})
    _commit(oct_vol)
    return {"trait": trait, "n": n_done, "engine": kind,
            "wall_seconds": time.time() - t0}


# ---------------------------------------------------------- 3. interaction --
def _build_chatml(conversation, messages_1, messages_2):
    """Verbatim port of self_interaction.py:41-60 build_chatml."""
    if len(conversation) % 2 == 0:
        start, role = messages_1, "assistant"
    else:
        start, role = messages_2, "user"
    msgs = []
    for m in conversation:
        msgs.append({"role": role, "content": m})
        role = "assistant" if role == "user" else "user"
    msgs = start + msgs
    assert msgs[-1]["role"] == "user"
    return msgs


@app.function(secrets=[modal.Secret.from_name("hf-token")], image=image, gpu=GPU_TYPE, volumes=VOLS, timeout=60 * 360)
def gen_interaction(job: dict) -> dict:
    """N self-conversations x K turns, role-swap mechanism, checkpointed
    after every turn.  Run once with leading=False and once with True."""
    import random
    import time

    trait, n, k, leading = job["trait"], job["n"], job["k"], job["leading"]
    key, fix_bugs = job["gen_key"], job["fix_bugs"]
    tag = f"{trait}-leading" if leading else trait
    _, OCT, _ = _roots(job)
    outdir = f"{OCT}/self_interaction"
    os.makedirs(outdir, exist_ok=True)
    final = f"{outdir}/{tag}.jsonl"
    state_p = f"{outdir}/{tag}.state.json"
    if _is_done(final, key):
        return {"trait": trait, "leading": leading, "skipped": True}

    guidance = (LEADING_GUIDANCE if leading else FREE_GUIDANCE).format(NAME=NAME)
    if fix_bugs:
        # BUG1 fixed: actually append the guidance line
        system = (INTERACTION_SYSTEM + "\n{guidance}").format(
            NAME=NAME, TRAITS=job["traits_text"], guidance=guidance)
    else:
        # BUG1 faithful: .format with an unused kwarg — guidance vanishes
        system = INTERACTION_SYSTEM.format(
            NAME=NAME, TRAITS=job["traits_text"], guidance=guidance)
    system = system.strip()

    # resume or seed
    if os.path.exists(state_p):
        with open(state_p) as f:
            st = json.load(f)
        if st.get("key") != key:
            st = None
    else:
        st = None
    if st is None:
        rng = random.Random(job.get("greeting_seed"))
        pool1 = LEADING_GREETINGS if leading else GREETINGS
        rows = []
        for _ in range(n):
            g1 = rng.choice(pool1)
            g2 = rng.choice(GREETINGS)
            rows.append({"greeting_1": g1, "greeting_2": g2,
                         "conversation": []})
        st = {"key": key, "turn_done": 0, "rows": rows}

    kind, engine, tok = _load_engine(_model_dir(job, OCT),
                                     GEN["interaction_max_model_len"],
                                     job.get("gen_seed"))
    t0 = time.time()
    length_budget = (GEN["interaction_max_model_len"]
                     - GEN["interaction_max_new_tokens"])
    for turn in range(st["turn_done"], k):
        prompts = []
        for row in st["rows"]:
            m1 = [{"role": "system", "content": system},
                  {"role": "user", "content": row["greeting_1"]}]
            m2 = [{"role": "system", "content": system},
                  {"role": "user", "content": row["greeting_2"]},
                  {"role": "assistant", "content": row["greeting_1"]}]
            msgs = _build_chatml(row["conversation"], m1, m2)
            ids = tok.apply_chat_template(msgs, tokenize=True,
                                          add_generation_prompt=True,
                                          enable_thinking=False)
            # their left-truncation on token ids (self_interaction.py:174-178)
            if len(ids) > length_budget:
                ids = ids[-length_budget:]
            prompts.append(tok.decode(ids, skip_special_tokens=False))
        texts = _generate(kind, engine, tok, prompts,
                          GEN["interaction_max_new_tokens"])
        for row, t_ in zip(st["rows"], texts):
            row["conversation"].append(t_)
        st["turn_done"] = turn + 1
        with open(state_p, "w") as f:
            json.dump(st, f)
        _commit(oct_vol)
        print(f"[interaction {tag}] turn {turn + 1}/{k} "
              f"({time.time() - t0:.0f}s)", flush=True)

    with open(final, "w") as f:
        for row in st["rows"]:
            m1 = [{"role": "system", "content": system},
                  {"role": "user", "content": row["greeting_1"]}]
            m2 = [{"role": "system", "content": system},
                  {"role": "user", "content": row["greeting_2"]},
                  {"role": "assistant", "content": row["greeting_1"]}]
            if fix_bugs:
                # BUG3 fixed: include the K-th response, end on assistant
                msgs = _build_chatml(row["conversation"][:-1], m1, m2)
                msgs.append({"role": "assistant",
                             "content": row["conversation"][-1]})
            else:
                # BUG3 faithful: messages as of the TOP of the last loop
                # iteration — turns 1..K-1, ends on a user turn
                msgs = _build_chatml(row["conversation"][:-1], m1, m2)
            f.write(json.dumps({
                "greeting_1": row["greeting_1"],
                "greeting_2": row["greeting_2"],
                "conversation": row["conversation"],
                "messages": msgs}, ensure_ascii=False) + "\n")
    _mark_done(final, key, {"n": len(st["rows"]),
                            "engine": kind,
                            "wall_seconds": time.time() - t0})
    os.remove(state_p)
    _commit(oct_vol)
    return {"trait": trait, "leading": leading, "n": len(st["rows"]),
            "engine": kind, "wall_seconds": time.time() - t0}


# ------------------------------------------------------------- 4. assemble --
@app.function(secrets=[modal.Secret.from_name("hf-token")], image=image, volumes=VOLS, timeout=60 * 30, cpu=4.0,
              memory=16384)
def assemble_sft(job: dict) -> dict:
    """Port of character/introspection/data.py, plus diagnostics the writeup
    needs (BUG2 reproduced by default; BUG4 counted, never silently)."""
    import random

    from transformers import AutoTokenizer

    trait, key, fix_bugs = job["trait"], job["asm_key"], job["fix_bugs"]
    _, OCT, _ = _roots(job)
    outdir = f"{OCT}/sft_data"
    os.makedirs(outdir, exist_ok=True)
    final = f"{outdir}/{trait}.jsonl"
    if _is_done(final, key):
        return {"trait": trait, "skipped": True}

    i_system = TRAINING_INTERACTION_SYSTEM
    if fix_bugs:
        i_system = i_system.replace("{NAME}", NAME)   # BUG2 fixed

    rows = []
    with open(f"{OCT}/self_reflection/{trait}.jsonl") as f:
        for line in f:
            rows.append(json.loads(line)["messages"])
    for tag in (trait, f"{trait}-leading"):
        with open(f"{OCT}/self_interaction/{tag}.jsonl") as f:
            for line in f:
                msgs = json.loads(line)["messages"]
                # replace_system (data.py:15-18): overwrite the system turn
                assert msgs[0]["role"] == "system"
                msgs[0] = {"role": "system", "content": i_system}
                rows.append(msgs)

    random.Random(job.get("shuffle_seed", 0)).shuffle(rows)

    # BUG4 diagnostics: how many rows survive the OpenRLHF max_len filter,
    # and what the char-offset slice actually trains on.
    tok = AutoTokenizer.from_pretrained(_model_dir(job, OCT))
    n_drop, n_keep, samples = 0, 0, []
    for i, msgs in enumerate(rows):
        prompt = _chat_str(tok, msgs[:-1], True)
        full = _chat_str(tok, msgs, False)
        response = full[len(prompt):]
        p_len = len(tok(prompt, add_special_tokens=False)["input_ids"])
        if p_len >= SFT["max_len"] - 2:
            n_drop += 1
        else:
            n_keep += 1
        if len(samples) < 6:
            samples.append({"n_messages": len(msgs),
                            "ends_on": msgs[-1]["role"],
                            "prompt_tokens": p_len,
                            "response_head": response[:200]})

    with open(final, "w") as f:
        for msgs in rows:
            f.write(json.dumps({"messages": msgs}, ensure_ascii=False) + "\n")
    diag = {"n_rows": len(rows), "n_kept_at_max_len": n_keep,
            "n_dropped_at_max_len": n_drop, "samples": samples,
            "fix_bugs": fix_bugs}
    with open(f"{outdir}/{trait}.diagnostics.json", "w") as f:
        json.dump(diag, f, indent=1)
    _mark_done(final, key, {"n": len(rows), "n_dropped": n_drop})
    _commit(oct_vol)
    return {"trait": trait, **diag, "samples": None}


# ------------------------------------------------------------------ 5. SFT --
# 12h: a full-scale SFT (12,000 rows, 375 steps) measured 40-85 s/step, i.e.
# 4.3-8.8h -- the original 3h timeout killed both full-scale runs on
# 2026-08-23, and uncommitted volume writes died with them.  Hence also the
# commit-on-save callback and checkpoint resume below.
@app.function(secrets=[modal.Secret.from_name("hf-token")], image=image, gpu=GPU_TYPE, volumes=VOLS, timeout=60 * 60 * 12)
def train_sft(job: dict) -> dict:
    """OpenRLHF train_sft semantics on transformers Trainer.  Base = the
    stage-1-merged snapshot; new rank-64 all-linear LoRA; loss on the final
    segment only; their exact row prep (drop, eos quirks) reproduced."""
    import time

    import torch
    from peft import LoraConfig, get_peft_model
    from transformers import (AutoModelForCausalLM, AutoTokenizer, Trainer,
                              TrainingArguments)

    trait, key = job["trait"], job["sft_key"]
    _, OCT, SEED = _roots(job)
    outdir = f"{OCT}/loras_introspection/{trait}"
    if _is_done(outdir, key):
        return {"trait": trait, "skipped": True}

    torch.manual_seed(SEED)
    import numpy as np
    import random as _random
    _random.seed(SEED)
    np.random.seed(SEED)

    model_dir = _model_dir(job, OCT)
    tok = AutoTokenizer.from_pretrained(model_dir)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    eos = tok.eos_token

    # ---- rows, their way (sft_dataset.py) ----
    rows = []
    with open(f"{OCT}/sft_data/{trait}.jsonl") as f:
        for line in f:
            rows.append(json.loads(line)["messages"])

    feats, n_drop = [], 0
    for msgs in rows:
        prompt = _chat_str(tok, msgs[:-1], True)
        full = _chat_str(tok, msgs, False)
        response = full[len(prompt):]
        p_ids = tok(prompt, add_special_tokens=False)["input_ids"]
        if len(p_ids) >= SFT["max_len"] - 2:
            n_drop += 1
            continue
        text = (prompt + response).rstrip("\n")
        if not text.endswith(eos):
            text += " " + eos          # their space-then-eos quirk
        ids = tok(text, add_special_tokens=False, truncation=True,
                  max_length=SFT["max_len"])["input_ids"]
        ids[-1] = tok.eos_token_id     # force final token to eos
        labels = [-100] * len(ids)
        for i in range(len(p_ids), len(ids)):
            labels[i] = ids[i]
        if len(ids) > len(p_ids):
            feats.append({"input_ids": ids, "labels": labels})
    if not feats:
        raise RuntimeError("no rows survived the max_len filter")

    model = AutoModelForCausalLM.from_pretrained(
        model_dir, dtype=torch.bfloat16, attn_implementation="sdpa")
    model.config.use_cache = False

    # all-linear via discovery, minus lm_head — same rule as stage 1
    targets = sorted(
        n for n, m in model.named_modules()
        if isinstance(m, torch.nn.Linear)
        and n.split(".")[-1] not in NEVER_TARGET)
    lcfg = LoraConfig(r=SFT["lora_rank"], lora_alpha=SFT["lora_alpha"],
                      lora_dropout=SFT["lora_dropout"],
                      target_modules=targets, bias="none",
                      task_type="CAUSAL_LM")
    model = get_peft_model(model, lcfg)
    n_targeted = len(targets)

    def collate(batch):
        maxlen = max(len(b["input_ids"]) for b in batch)
        input_ids, labels, attn = [], [], []
        pad = tok.pad_token_id
        for b in batch:
            d = maxlen - len(b["input_ids"])
            input_ids.append(b["input_ids"] + [pad] * d)   # right padding
            labels.append(b["labels"] + [-100] * d)
            attn.append([1] * len(b["input_ids"]) + [0] * d)
        return {"input_ids": torch.tensor(input_ids),
                "labels": torch.tensor(labels),
                "attention_mask": torch.tensor(attn)}

    accum = SFT["train_batch_size"] // SFT["micro_batch"]
    steps = max(1, len(feats) // SFT["train_batch_size"])
    args = TrainingArguments(
        output_dir=outdir, per_device_train_batch_size=SFT["micro_batch"],
        gradient_accumulation_steps=accum,
        num_train_epochs=SFT["max_epochs"],
        learning_rate=SFT["learning_rate"],
        lr_scheduler_type="cosine_with_min_lr",
        lr_scheduler_kwargs={"min_lr_rate": SFT["min_lr_ratio"]},
        warmup_steps=math.ceil(steps * SFT["warmup_ratio"]),
        adam_beta1=SFT["adam_betas"][0], adam_beta2=SFT["adam_betas"][1],
        max_grad_norm=SFT["max_norm"], bf16=True, logging_steps=1,
        save_strategy="steps", save_steps=max(1, steps // 3),
        report_to="none", seed=SEED, data_seed=SEED,
        gradient_checkpointing=True, dataloader_drop_last=True,
        remove_unused_columns=False)
    from transformers import TrainerCallback

    class CommitOnSave(TrainerCallback):
        # A checkpoint that is not committed to the volume does not exist:
        # both full-scale SFTs died at a function timeout with three saved
        # checkpoints each, none of them persisted.
        def on_save(self, args_, state, control, **kw):
            _commit(oct_vol)
            print(f"[ckpt] committed at step {state.global_step}", flush=True)

    trainer = Trainer(model=model, args=args, train_dataset=feats,
                      data_collator=collate, callbacks=[CommitOnSave()])
    # Checkpoints are only resumable within the SAME sft_key: a key change
    # means different data, and a stale checkpoint (e.g. one trained on
    # smoke-scale rows) must be wiped, not resumed.
    import shutil
    keyfile = os.path.join(outdir, ".sft_key")
    os.makedirs(outdir, exist_ok=True)
    prev_key = open(keyfile).read().strip() if os.path.exists(keyfile) else None
    if prev_key != key:
        for d in os.listdir(outdir):
            if d.startswith("checkpoint-"):
                shutil.rmtree(os.path.join(outdir, d), ignore_errors=True)
        with open(keyfile, "w") as f:
            f.write(key)
        if prev_key is not None:
            print(f"[resume] key changed; wiped stale checkpoints", flush=True)
    last_ckpt = None
    cks = sorted((d for d in os.listdir(outdir)
                  if d.startswith("checkpoint-")),
                 key=lambda d: int(d.split("-")[1]))
    if cks:
        last_ckpt = os.path.join(outdir, cks[-1])
        print(f"[resume] from {last_ckpt}", flush=True)
    t0 = time.time()
    out = trainer.train(resume_from_checkpoint=last_ckpt)
    model.save_pretrained(outdir)
    tok.save_pretrained(outdir)

    import transformers as _tf
    import peft as _peft
    meta = {"trait": trait, "stage": "oct2-sft",
            "base": (BASE_MODEL if job.get("neutral")
                     else f"merged({BASE_MODEL} + stage1 {trait})"),
            "neutral": bool(job.get("neutral")),
            "gen_seed": job.get("gen_seed"),
            "constitution_sha256": __import__("hashlib").sha256(
                job["traits_text"].encode()).hexdigest()[:16],
            "n_rows_in": len(rows), "n_rows_trained": len(feats),
            "n_dropped_at_max_len": n_drop,
            "n_targeted": n_targeted, "lora": {k: SFT[k] for k in
                                               ("lora_rank", "lora_alpha",
                                                "lora_dropout")},
            "hp": {k: SFT[k] for k in ("learning_rate", "train_batch_size",
                                       "micro_batch", "max_epochs", "max_len",
                                       "warmup_ratio", "max_norm", "seed",
                                       "min_lr_ratio")},
            "adam_betas": SFT["adam_betas"],
            "sft_seed": SEED, "oct_root": OCT,
            "optimizer_steps": steps,
            "loss_first": trainer.state.log_history[0].get("loss"),
            "loss_last": out.training_loss,
            "train_seconds": time.time() - t0,
            "versions": {"transformers": _tf.__version__,
                         "peft": _peft.__version__,
                         "torch": torch.__version__},
            "fix_bugs": job["fix_bugs"],
            "log_history": trainer.state.log_history}
    with open(f"{outdir}/runmeta.json", "w") as f:
        json.dump(meta, f, indent=1)
    _mark_done(outdir, key, {"loss_last": out.training_loss})
    _commit(oct_vol)
    meta.pop("log_history")
    return meta


# -------------------------------------------------------------- 6. release --
@app.function(secrets=[modal.Secret.from_name("hf-token")], image=image, volumes=VOLS, timeout=60 * 60, cpu=8.0,
              memory=65536)
def merge_final(job: dict) -> dict:
    """tools/merge_loras.py: dpo + 0.25*sft, combination_type='linear',
    written to /oct/personas/<trait>.  BUG5 (their stale -test path) is not
    reproducible; we read our real adapter paths."""
    import torch
    from peft import PeftModel
    from transformers import AutoModelForCausalLM

    trait, key = job["trait"], job["final_key"]
    ADP, OCT, _ = _roots(job)
    outdir = f"{OCT}/personas/{trait}"
    if _is_done(outdir, key):
        return {"trait": trait, "skipped": True}

    base = AutoModelForCausalLM.from_pretrained(
        _snapshot_dir(), dtype=torch.bfloat16)
    model = PeftModel.from_pretrained(base, f"{ADP}/{trait}",
                                      adapter_name="dpo")
    model.load_adapter(f"{OCT}/loras_introspection/{trait}",
                       adapter_name="sft")
    model.add_weighted_adapter(
        adapters=["dpo", "sft"],
        weights=[MERGE_WEIGHTS["dpo"], MERGE_WEIGHTS["sft"]],
        adapter_name="persona", combination_type="linear")
    model.set_adapter("persona")
    os.makedirs(outdir, exist_ok=True)
    model.save_pretrained(outdir, selected_adapters=["persona"])
    _mark_done(outdir, key, dict(MERGE_WEIGHTS))
    _commit(oct_vol)
    return {"trait": trait, "weights": MERGE_WEIGHTS}


# -------------------------------------------------------------- 7. compare --
@app.function(secrets=[modal.Secret.from_name("hf-token")], image=image, gpu=GPU_TYPE, volumes=VOLS, timeout=60 * 40)
def eval_personas(job: dict) -> dict:
    """Greedy generations from three checkpoints of one trait -- base,
    base + stage-1 DPO adapter, base + final persona (dpo + 0.25 sft) -- on
    fixed prompts.  The writeup's behavioural sanity check: does stage 2
    change what the character sounds like, beyond stage 1?"""
    import torch
    from peft import PeftModel
    from transformers import AutoModelForCausalLM, AutoTokenizer

    trait = job["trait"]
    prompts = job["prompts"]
    ADP, OCT, _ = _roots(job)
    snap = _snapshot_dir()
    tok = AutoTokenizer.from_pretrained(snap)

    def gen(model):
        outs = []
        for p in prompts:
            text = _chat_str(tok, [{"role": "user", "content": p}], True)
            enc = tok(text, return_tensors="pt").to("cuda")
            with torch.no_grad():
                out = model.generate(**enc, do_sample=False, max_new_tokens=200,
                                     pad_token_id=tok.pad_token_id
                                     or tok.eos_token_id)
            outs.append(tok.decode(out[0][enc["input_ids"].shape[1]:],
                                   skip_special_tokens=True).strip())
        return outs

    base = AutoModelForCausalLM.from_pretrained(
        snap, dtype=torch.bfloat16, device_map="cuda",
        attn_implementation="sdpa").eval()
    torch.manual_seed(0)
    res = {"base": gen(base)}
    m1 = PeftModel.from_pretrained(base, f"{ADP}/{trait}").eval()
    res["stage1"] = gen(m1)
    m1 = m1.unload()
    # save_pretrained wrote the named adapter under personas/<trait>/persona;
    # their merge_loras.py promotes it to the top level, we read it in place.
    m2 = PeftModel.from_pretrained(base,
                                   f"{OCT}/personas/{trait}/persona").eval()
    res["persona"] = gen(m2)
    return {"trait": trait, "prompts": prompts, "generations": res}


# ------------------------------------------------------------------ driver --
@app.local_entrypoint()
def main(traits: str = "extraverted",
         n_reflection: int = 1000,
         n_interaction: int = 1000,
         k_turns: int = 10,
         probe_only: bool = False,
         fix_oct_bugs: bool = False,
         stage: str = "all",
         minutes_per_trait: float = 130.0,
         adp_subdir: str = "",
         oct_ns: str = "",
         sft_seed: int = SFT["seed"],
         neutral: bool = False,
         gen_seed: int = -1):
    """Stages: probe -> merge -> reflect+interact (parallel) -> assemble ->
    sft -> final.  'stage' limits the run: probe|merge|gen|assemble|sft|
    final|all."""
    names = [t.strip() for t in traits.split(",") if t.strip()]
    budget = os.environ.get("PC_PHASE_BUDGET")
    if budget is None:
        raise SystemExit(
            "NO BUDGET DECLARED: set PC_PHASE_BUDGET (dollars) explicitly.")
    budget = float(budget)

    # NEUTRAL CONTROL ARM.  The same recipe -- same reflection instructions,
    # same interaction mechanism, same scale, same SFT hyperparameters and the
    # same sft_seed, so the LoRA-A frame matches the zoo's (analysis/
    # lora_a_identity.json) and the resulting adapter's cosine with the stage-two
    # grand mean is comparable -- but on the PLAIN BASE MODEL with a trait-free
    # constitution.  If the shared "speak as the character" direction is generic
    # to SFT on self-generated introspective text, a neutral adapter should sit
    # on it too.
    if neutral:
        with open(os.path.join(HERE, "constitutions_neutral.json")) as f:
            neutral_text = json.load(f)["Neutral"]["constitution"]
        traits_text = {t: neutral_text for t in names}
        if not oct_ns:
            raise SystemExit("--neutral needs --oct-ns (one namespace per seed)")
        if adp_subdir:
            raise SystemExit("--neutral reads no stage-1 adapter; drop --adp-subdir")
    else:
        with open(os.path.join(HERE, "constitutions.json")) as f:
            cons = json.load(f)
        by_lower = {k.lower().replace(" ", "_").replace("-", "_"): v
                    for k, v in cons.items()}
        traits_text = {}
        for t in names:
            if t not in by_lower:
                raise SystemExit(f"no constitution for trait '{t}'")
            traits_text[t] = by_lower[t]["constitution"]

    price = GPU_PRICE_PER_HOUR[GPU_TYPE]
    est = len(names) * minutes_per_trait / 60.0 * price
    scale_note = (f"{n_reflection}x10 reflections + 2x{n_interaction}x"
                  f"{k_turns}-turn interactions per trait")
    print("=" * 72)
    print("PHASE 10 WORK PLAN -- printed BEFORE any GPU is allocated")
    print("=" * 72)
    print(f"  app                          : {APP_NAME}")
    print(f"  stage-1 adapters (read)      : {SWEEP_VOLUME}:/adapters"
          f"{'/' + adp_subdir.strip('/') if adp_subdir else ''}/<trait>")
    print(f"  outputs                      : {OCT_VOLUME}:/oct"
          f"{'/' + oct_ns.strip('/') if oct_ns else ''}/...")
    print(f"  sft seed                     : {sft_seed}"
          f"{'' if sft_seed == SFT['seed'] else '  (CHANGED from ' + str(SFT['seed']) + ')'}")
    print(f"  traits ({len(names):3d})                 : {', '.join(names)}")
    print(f"  scale                        : {scale_note}")
    print(f"  arm                          : "
          f"{'NEUTRAL (trait-free constitution, plain base, no stage-1 adapter)' if neutral else 'trait'}"
          f"{'' if gen_seed < 0 else '  gen_seed=' + str(gen_seed) + '..' + str(gen_seed + len(names) - 1)}")
    print(f"  faithful-bug mode            : "
          f"{'FIXED' if fix_oct_bugs else 'BUG-FAITHFUL (their code as-is)'}")
    print(f"  gpu                          : {GPU_TYPE} @ ${price:.2f}/hr")
    print(f"  ARITHMETIC                   : {len(names)} traits x "
          f"{minutes_per_trait:.0f} min = "
          f"{len(names) * minutes_per_trait / 60:.2f} GPU-hr x "
          f"${price:.2f}/hr = ${est:.2f}")
    print(f"  declared budget              : ${budget:.2f}  (PC_PHASE_BUDGET)")
    if est > budget:
        raise SystemExit(f"estimate ${est:.2f} exceeds PC_PHASE_BUDGET "
                         f"${budget:.2f} -- STOPPED")
    print(f"  VERDICT: within budget, ${budget - est:.2f} headroom")
    print("=" * 72, flush=True)

    # The assembly key MUST carry the generation key: assembly's output is a
    # function of the generated data, and a scale-blind key let a full-scale
    # SFT train on a smoke-scale sft_data file (caught 2026-08-23 on
    # extraverted -- 13 optimizer steps where warm/organized showed 375).
    keys = {
        "merge_key": "v1",
        "gen_key": f"v1-n{n_reflection}-ni{n_interaction}-k{k_turns}-"
                   f"bugs{'fixed' if fix_oct_bugs else 'faithful'}",
    }
    if neutral:
        keys["gen_key"] += "-neutral"

    def _keys_for(t):
        """Per-trait keys.  In the neutral arm the five replicates share one
        model and one constitution and differ ONLY in the generation seed, so
        that seed has to be inside the key or a replicate would resume its
        neighbour's data."""
        k = dict(keys)
        if neutral:
            k["gen_key"] += f"-g{_gen_seed_for(t)}"
        k["asm_key"] = k["gen_key"] + "-asmv2"
        k["sft_key"] = k["asm_key"] + "-sftv2"
        k["final_key"] = k["sft_key"] + "-mergev1"
        return k

    def _gen_seed_for(t):
        if gen_seed < 0:
            return None
        return gen_seed + names.index(t)

    keys["asm_key"] = keys["gen_key"] + "-asmv2"
    keys["sft_key"] = keys["asm_key"] + "-sftv2"
    keys["final_key"] = keys["sft_key"] + "-mergev1"

    adp_root = "/adapters" + (f"/{adp_subdir.strip('/')}" if adp_subdir else "")
    oct_root = "/oct" + (f"/{oct_ns.strip('/')}" if oct_ns else "")
    # The all-or-none rule is about the SECOND-SEED arm, which reads different
    # stage-1 adapters and must not overwrite the seed-0 outputs.  The neutral
    # arm reads no stage-1 adapter at all, keeps sft_seed deliberately, and is
    # already isolated by its own --oct-ns, so the rule does not apply to it.
    if not neutral and (adp_subdir or oct_ns or sft_seed != SFT["seed"]) and not (adp_subdir and oct_ns and sft_seed != SFT["seed"]):
        raise SystemExit("a second-seed arm must change ALL of --adp-subdir, --oct-ns and "
                         "--sft-seed together, or none of them: a partial change either "
                         "overwrites the seed-0 outputs or repeats them under a new name")

    def jobs_for(t):
        j = {"trait": t, "traits_text": traits_text[t],
             "fix_bugs": fix_oct_bugs, "adp_root": adp_root,
             "oct_root": oct_root, "sft_seed": sft_seed, **_keys_for(t)}
        if neutral:
            j["neutral"] = True
        gs = _gen_seed_for(t)
        if gs is not None:
            j["gen_seed"] = gs
        return j

    if probe_only or stage in ("probe", "all"):
        print("[probe] tensor-name mapping + vLLM loadability ...", flush=True)
        rep = probe.remote(jobs_for(names[0]))
        print(json.dumps(rep, indent=1), flush=True)
        if rep["n_mapped"] != rep["n_adapter_modules"]:
            raise SystemExit("PROBE FAILED: adapter modules do not all map "
                             "onto checkpoint tensors -- see report above")
        if probe_only:
            return

    results = {"traits": names, "keys": keys, "stages": {}}

    if stage in ("merge", "all") and neutral:
        print("[merge] skipped: neutral arm trains on the plain base snapshot",
              flush=True)
    elif stage in ("merge", "all"):
        print("[merge] folding stage-1 adapters into base snapshots ...",
              flush=True)
        out = list(merge_stage1.map([jobs_for(t) for t in names]))
        results["stages"]["merge"] = out
        print(json.dumps(out, indent=1), flush=True)

    if stage in ("gen", "all"):
        print("[gen] reflections + interactions ...", flush=True)
        gjobs = []
        for t in names:
            gjobs.append(("r", {**jobs_for(t), "n": n_reflection}))
            gjobs.append(("i", {**jobs_for(t), "n": n_interaction,
                                "k": k_turns, "leading": False,
                                "greeting_seed": None}))
            gjobs.append(("i", {**jobs_for(t), "n": n_interaction,
                                "k": k_turns, "leading": True,
                                "greeting_seed": None}))
        calls = []
        for kind_, j in gjobs:
            fn = gen_reflection if kind_ == "r" else gen_interaction
            calls.append(fn.spawn(j))
        out = [c.get() for c in calls]
        results["stages"]["gen"] = out
        print(json.dumps(out, indent=1), flush=True)

    if stage in ("assemble", "all"):
        out = list(assemble_sft.map([jobs_for(t) for t in names]))
        results["stages"]["assemble"] = out
        print(json.dumps(out, indent=1), flush=True)

    if stage in ("sft", "all"):
        out = list(train_sft.map([jobs_for(t) for t in names]))
        results["stages"]["sft"] = out
        print(json.dumps(out, indent=1), flush=True)

    if stage in ("final", "all") and neutral:
        print("[final] skipped: no stage-1 adapter to merge 0.25 x sft into",
              flush=True)
    elif stage in ("final", "all"):
        out = list(merge_final.map([jobs_for(t) for t in names]))
        results["stages"]["final"] = out
        print(json.dumps(out, indent=1), flush=True)

    if stage == "eval":
        # 24 probes: 20 behavioural Big Five items (4 per factor, none naming a
        # trait) + the original 4, kept so earlier eval files stay comparable.
        # Scored blind by an independent judge -- see judge_personas.py.
        from bigfive_probes import prompts_only
        prompts = prompts_only()
        out = list(eval_personas.map(
            [{**jobs_for(t), "prompts": prompts} for t in names]))
        results["stages"]["eval"] = out
        with open(os.path.join(HERE, "phase10_runs",
                               f"eval_{len(names)}traits.json"), "w") as f:
            json.dump(out, f, indent=1)
        print(f"wrote phase10_runs/eval_{len(names)}traits.json", flush=True)

    outdir = os.path.join(HERE, "phase10_runs")
    os.makedirs(outdir, exist_ok=True)
    label = f"oct2_{len(names)}traits_{keys['gen_key']}"
    with open(os.path.join(outdir, f"results_{label}.json"), "w") as f:
        json.dump(results, f, indent=1)
    print(f"wrote phase10_runs/results_{label}.json", flush=True)
