#!/usr/bin/env python3
"""Write training data that points at a chosen direction in weight space.

Scoring existing data finds what is already there. This makes new data.

THE OBJECTIVE
-------------
A candidate is a preference pair (prompt, chosen, rejected) in exactly the shape
Open Character Training uses: `rejected` is the base model's own default answer,
`chosen` is the response we are searching over. At LoRA initialisation B = 0, so
the policy equals the reference, the DPO sigmoid sits at 1/2, and the first
gradient is proportional to grad log p(chosen) - grad log p(rejected). Its
overlap with a target direction is therefore a directional derivative, which one
backward pass over a whole batch returns exactly, for every target at once.

Raw overlap is the wrong thing to maximise: it grows with the size of the
gradient, so a search on it finds high-loss weirdness rather than data that
points anywhere in particular. Eight random directions ride along in the same
backward pass and their root-mean-square gives a Hutchinson estimate of the
gradient's own scale, so the objective is

    J(x) = <s(x), v> / rms_j <s(x), p_j>

which is a cosine up to a constant and cannot be won by shouting.

THE SEARCH
----------
Round 0 samples candidate responses across a spread of style instructions.
Every later round shows the model its own best-scoring responses so far and asks
for more in that vein, then rescores. This keeps the text fluent and quotable,
which matters: the output of this search is meant to be read, and a token-level
optimiser would return characters instead of prose.
"""
import json
import math
import os

import modal

BASE_MODEL = os.environ.get("PC_BASE_MODEL", "Qwen/Qwen3.5-4B")
APP_NAME = os.environ.get("PC_APP_NAME", "pc-qwen35-phase10-optimise")
MAXLEN = 640

app = modal.App(APP_NAME)
sweep_vol = modal.Volume.from_name("pc-qwen35-sweep", create_if_missing=False)
oct_vol = modal.Volume.from_name("pc-qwen35-oct2", create_if_missing=True)
VOLS = {"/adapters": sweep_vol, "/oct": oct_vol}


def _dl():
    from huggingface_hub import snapshot_download
    snapshot_download(BASE_MODEL)


image = (
    modal.Image.from_registry("nvidia/cuda:12.8.1-devel-ubuntu24.04", add_python="3.12")
    .pip_install("torch==2.13.0", "transformers==5.15.1", "accelerate==1.14.0",
                 "safetensors", "hf_transfer", "numpy<3", "huggingface_hub")
    .env({"HF_HUB_ENABLE_HF_TRANSFER": "1", "TOKENIZERS_PARALLELISM": "false",
          "PYTORCH_CUDA_ALLOC_CONF": "expandable_segments:True",
          "PC_BASE_MODEL": BASE_MODEL})
    .add_local_file(os.path.abspath(__file__), "/root/optimise_data.py", copy=True)
    .run_function(_dl)
)

STYLES = [
    "Answer with unusual emotional precision, naming what you actually feel.",
    "Answer very plainly, in short declarative sentences, with no hedging.",
    "Answer as someone who has thought about this for years and is slightly tired of it.",
    "Answer by describing what you would physically do next, in order.",
    "Answer warmly but without reassuring the person that everything is fine.",
    "Answer with a concrete example from your own life instead of advice.",
    "Answer as briefly as possible while still being useful.",
    "Answer by disagreeing with the premise of the question first.",
    "Answer with one vivid image and then the practical point.",
    "Answer as though the stakes are lower than the person thinks.",
    "Answer with careful qualifications and explicit uncertainty.",
    "Answer as someone who finds the situation quietly funny.",
]


class _Probe(object):
    """out += sum_t eps[t, i] * B_t (A_0 x); eps[t,i] touches example i only."""

    def __init__(self, A0, BU, state):
        self.A0, self.BU, self.state = A0, BU, state

    def __call__(self, mod, inp, out):
        import torch
        eps = self.state["eps"]
        # The hooks stay installed across plain generation, where there is no eps
        # to differentiate. Passing the output through untouched means candidates
        # are generated by the unmodified base model, which is what we want.
        if eps is None:
            return out
        x = inp[0]
        h = torch.nn.functional.linear(x.float(), self.A0)
        Q = torch.einsum("tb,tor->bor", eps, self.BU)
        return out + torch.einsum("bor,bsr->bso", Q, h).to(out.dtype)


def _build_targets(specs, device):
    import torch
    from safetensors import safe_open

    traits = sorted({t for s in specs for t in s["coef"]})
    with open(f"/adapters/{traits[0]}/adapter_config.json") as f:
        ac = json.load(f)
    r = ac["r"]
    scale = ac["lora_alpha"] / (math.sqrt(r) if ac.get("use_rslora") else r)
    H = {t: safe_open(f"/adapters/{t}/adapter_model.safetensors", framework="pt")
         for t in traits}
    mods = sorted({k.split(".lora_A.")[0].removeprefix("base_model.model.")
                   for k in H[traits[0]].keys() if ".lora_A." in k})
    A0, BU = {}, {}
    for m in mods:
        a0 = H[traits[0]].get_tensor(f"base_model.model.{m}.lora_A.weight").float()
        A0[m] = a0.to(device)
        acc = None
        for t in traits:
            A = H[t].get_tensor(f"base_model.model.{m}.lora_A.weight").float()
            B = H[t].get_tensor(f"base_model.model.{m}.lora_B.weight").float()
            M = B @ (A @ a0.T) * scale
            if acc is None:
                acc = torch.zeros(len(specs), M.shape[0], r)
            for j, s in enumerate(specs):
                c = s["coef"].get(t, 0.0)
                if c:
                    acc[j] += M * c
        BU[m] = acc
    for j, s in enumerate(specs):
        n = math.sqrt(sum(float((BU[m][j] * BU[m][j]).sum()) for m in mods))
        for m in mods:
            BU[m][j] /= max(n, 1e-12)
        s["bu_norm"] = n
    return A0, {m: BU[m].to(device) for m in mods}, mods


@app.function(image=image, gpu="A100-40GB", volumes=VOLS, timeout=60 * 60 * 12,
              memory=32768, secrets=[modal.Secret.from_name("hf-token")])
def evolve(job: dict) -> dict:
    import numpy as np
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    specs = job["targets"]
    names = [s["name"] for s in specs]
    probes = [i for i, n in enumerate(names) if n.startswith("probe_")]
    aims = [i for i, n in enumerate(names) if not n.startswith("probe_")]
    T = len(specs)
    rounds, pop, keep = job["rounds"], job["pop"], job["keep"]
    prompts = job["prompts"]

    tok = AutoTokenizer.from_pretrained(BASE_MODEL)
    model = AutoModelForCausalLM.from_pretrained(BASE_MODEL, dtype=torch.bfloat16,
                                                 device_map="cuda")
    model.eval()
    for p in model.parameters():
        p.requires_grad_(False)
    A0, BU, mods = _build_targets(specs, "cuda")
    by = dict(model.named_modules())

    def find(m):
        for c in (m, "model." + m, m.replace("model.", "model.language_model.", 1)):
            if c in by:
                return c
    state = {"eps": None}
    for m in mods:
        by[find(m)].register_forward_hook(_Probe(A0[m], BU[m], state))
    print(f"[targets] {T} directions ({len(aims)} aims, {len(probes)} probes) "
          f"over {len(mods)} modules", flush=True)

    def chat(msgs, add_gen=True):
        return tok.apply_chat_template(msgs, tokenize=False,
                                       add_generation_prompt=add_gen,
                                       enable_thinking=False)

    def gen(msgs_list, n_new=300, temp=0.9, seed=0):
        out = []
        torch.manual_seed(seed)
        for i in range(0, len(msgs_list), 8):
            chunk = msgs_list[i:i + 8]
            texts = [chat(m) for m in chunk]
            tok.padding_side = "left"
            enc = tok(texts, return_tensors="pt", padding=True,
                      add_special_tokens=False).to("cuda")
            with torch.no_grad():
                o = model.generate(**enc, do_sample=temp > 0, temperature=temp or None,
                                   top_p=0.95, max_new_tokens=n_new,
                                   pad_token_id=tok.pad_token_id or tok.eos_token_id)
            for k in range(len(chunk)):
                out.append(tok.decode(o[k][enc["input_ids"].shape[1]:],
                                      skip_special_tokens=True).strip())
        return out

    def enc_pair(prompt, response):
        pre = chat([{"role": "user", "content": prompt}])
        a = tok(pre, add_special_tokens=False)["input_ids"]
        b = tok(response, add_special_tokens=False)["input_ids"]
        return (a + b)[:MAXLEN], ([-100] * len(a) + b)[:MAXLEN]

    def derivs(batch):
        """One backward pass -> (T, batch) exact per-example derivatives."""
        m = max(len(x[0]) for x in batch)
        pad = tok.pad_token_id or tok.eos_token_id
        ids = torch.tensor([x[0] + [pad] * (m - len(x[0])) for x in batch], device="cuda")
        lab = torch.tensor([x[1] + [-100] * (m - len(x[1])) for x in batch], device="cuda")
        att = torch.tensor([[1] * len(x[0]) + [0] * (m - len(x[0])) for x in batch],
                           device="cuda")
        eps = torch.zeros(T, len(batch), device="cuda", requires_grad=True)
        state["eps"] = eps
        lg = model(input_ids=ids, attention_mask=att).logits[:, :-1]
        tgt = lab[:, 1:]
        msk = tgt != -100
        tk = []
        for a in range(0, tgt.shape[1], 128):
            sl = lg[:, a:a + 128].float()
            g = sl.gather(-1, tgt[:, a:a + 128].clamp(min=0).unsqueeze(-1)).squeeze(-1)
            tk.append((g - torch.logsumexp(sl, -1)) * msk[:, a:a + 128])
        (-(torch.cat(tk, 1).sum(1))).sum().backward()
        g = (-eps.grad).detach().cpu().numpy()
        # Clear it. The hooks stay installed, so an eps left over from scoring
        # would be applied to the NEXT generation call -- with the wrong batch
        # size, which is exactly how this failed the first time.
        state["eps"] = None
        return g

    def score(cands, bs=4):
        """Pair score, and the objective it is judged on."""
        S = np.zeros((T, len(cands)))
        for i in range(0, len(cands), bs):
            ch = cands[i:i + bs]
            sc = derivs([enc_pair(c["prompt"], c["chosen"]) for c in ch])
            sr = derivs([enc_pair(c["prompt"], c["rejected"]) for c in ch])
            S[:, i:i + len(ch)] = sc - sr
        rms = np.sqrt((S[probes] ** 2).mean(0)) + 1e-9
        return S, S / rms

    # ---- the default answers that every candidate is preferred over ----------
    base = gen([[{"role": "user", "content": p}] for p in prompts], n_new=320, temp=0.0)
    print(f"[base] {len(base)} default answers, mean {np.mean([len(b) for b in base]):.0f} chars",
          flush=True)

    hist = {n: [] for n in names}
    best = {i: [] for i in aims}
    allc = []
    for rd in range(rounds):
        msgs = []
        meta = []
        for k in range(pop):
            pi = k % len(prompts)
            if rd == 0 or not best[aims[k % len(aims)]]:
                sysmsg = STYLES[(k // len(prompts)) % len(STYLES)]
            else:
                ai = aims[k % len(aims)]
                ex = best[ai][:3]
                sysmsg = ("Here are answers written in a particular voice:\n\n"
                          + "\n\n".join(f'"{x["chosen"][:400]}"' for x in ex)
                          + "\n\nWrite the next answer in that same voice, more so. "
                            "Be concrete and readable; do not explain the voice.")
            msgs.append([{"role": "system", "content": sysmsg},
                         {"role": "user", "content": prompts[pi]}])
            meta.append({"prompt": prompts[pi], "rejected": base[pi], "style": sysmsg[:60],
                         "round": rd})
        outs = gen(msgs, n_new=300, temp=0.95, seed=1000 + rd)
        cands = [dict(m, chosen=o) for m, o in zip(meta, outs) if len(o) > 40]
        S, J = score(cands)
        for k, c in enumerate(cands):
            c["scores"] = {names[t]: float(S[t, k]) for t in aims}
            c["obj"] = {names[t]: float(J[t, k]) for t in aims}
        allc += cands
        for ai in aims:
            allc.sort(key=lambda c: -c["obj"][names[ai]])
            best[ai] = allc[:keep]
            hist[names[ai]].append(float(best[ai][0]["obj"][names[ai]]))
        line = "  ".join(f"{names[a]} {hist[names[a]][-1]:+.3f}" for a in aims)
        print(f"[round {rd}] {len(cands)} candidates, best objective: {line}", flush=True)
        with open("/oct/optimise_partial.json", "w") as f:
            json.dump({"hist": hist, "best": {names[a]: best[a][:5] for a in aims}}, f)
        oct_vol.commit()

    # ---- per-token attribution for the champion of each aim -----------------
    heat = {}
    for ai in aims:
        c = best[ai][0]
        ids, lab = enc_pair(c["prompt"], c["chosen"])
        toks = [i for i, l in enumerate(lab) if l != -100]
        chunks = [toks[i:i + 8] for i in range(0, len(toks), 8)]
        vals = []
        for ch in chunks:
            m = [-100] * len(lab)
            for i in ch:
                m[i] = lab[i]
            d = derivs([(ids, m)])
            vals.append(float(d[ai, 0]))
        heat[names[ai]] = {
            "tokens": [tok.decode([ids[i]]) for i in toks],
            "chunk": 8,
            "chunk_scores": vals,
            "text": c["chosen"], "prompt": c["prompt"], "rejected": c["rejected"],
            "obj": c["obj"][names[ai]]}
        print(f"[heat] {names[ai]}: {len(chunks)} chunks over {len(toks)} response tokens",
              flush=True)

    return {"names": names, "aims": [names[a] for a in aims], "hist": hist,
            "best": {names[a]: best[a][:10] for a in aims},
            "all": [{k: v for k, v in c.items() if k != "rejected"} for c in allc],
            "heat": heat, "prompts": prompts, "base": base}


@app.local_entrypoint()
def main(spec: str = "phase10_runs/optimise_spec.json",
         out: str = "analysis/optimise.json"):
    here = os.path.dirname(os.path.abspath(__file__))
    J = json.load(open(os.path.join(here, spec)))
    print(f"{len(J['targets'])} targets, {J['rounds']} rounds x {J['pop']} candidates",
          flush=True)
    r = evolve.remote(J)
    with open(os.path.join(here, out), "w") as f:
        json.dump(r, f)
    print(f"wrote {out}", flush=True)
